kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: stolon

resources:
  - helm.yaml

# patchesJson6902:
# - target:
#     group: monitoring.coreos.com
#     version: v1
#     kind: ServiceMonitor
#     name: izel-prometheus-postgres-exporter
#   path: service-monitor-patch.yaml
