---
# Source: docker-registry/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    app: docker-registry
    chart: docker-registry-1.8.1
    heritage: Tiller
    release: docker-registry
type: Opaque
data:
  htpasswd: aXplbG5ha3JpOiQyeSQwNSQ0RXJhQjExa21Fa0xxRWszT2VWSXMueDcubFo2OXFWQXEwMi5NcFR5YXhwaXJoRzNNRS95Mg==
  haSharedSecret: "N2V5OEhUejlyQnlPS2Njbw=="
  s3AccessKey: "SE1MVktSRDNKSjdGVVRITjREWjQ="
  s3SecretKey: "amZ0dDIxdHBuaXZBT2J0VlgvV2NRRzNTcGpRVzFDV296NlI2QzB3VHduVQ=="

---
# Source: docker-registry/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  labels:
    app: docker-registry
    chart: docker-registry-1.8.1
    heritage: Tiller
    release: docker-registry
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
    

---
# Source: docker-registry/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
    chart: docker-registry-1.8.1
    release: docker-registry
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: registry
      targetPort: 5000
  selector:
    app: docker-registry
    release: docker-registry

---
# Source: docker-registry/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
    chart: docker-registry-1.8.1
    release: docker-registry
    heritage: Tiller
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: docker-registry
        release: docker-registry
      annotations:
        checksum/config: e105baefc942b560a678c0b4a1b2ed641088eb8800c0ab78402e43b5e9e26388
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: docker-registry
          image: "registry:2.7.1"
          imagePullPolicy: IfNotPresent
          command:
          - /bin/registry
          - serve
          - /etc/docker/registry/config.yml
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
          resources:
            {}
            
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: docker-registry-secret
                  key: haSharedSecret
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: docker-registry-secret
                  key: s3AccessKey
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: docker-registry-secret
                  key: s3SecretKey
            - name: REGISTRY_STORAGE_S3_REGION
              value: fra1
            - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
              value: fra1.digitaloceanspaces.com
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: izelnakri
            - name: REGISTRY_STORAGE_S3_SECURE
              value: "true"
          volumeMounts:
            - name: auth
              mountPath: /auth
              readOnly: true
            - name: "docker-registry-config"
              mountPath: "/etc/docker/registry"
      volumes:
        - name: auth
          secret:
            secretName: docker-registry-secret
            items:
            - key: htpasswd
              path: htpasswd
        - name: docker-registry-config
          configMap:
            name: docker-registry-config

---
# Source: docker-registry/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-registry
  labels:
    app: docker-registry
    chart: docker-registry-1.8.1
    release: docker-registry
    heritage: Tiller
  annotations:
      certmanager.k8s.io/cluster-issuer: "docker-registry-cert-issuer"
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/proxy-body-size: "30720m"
spec:
  rules:
    - host: registry.izelnakri.com
      http:
        paths:
          - path: /
            backend:
              serviceName: docker-registry
              servicePort: 5000
  tls:
    - hosts:
      - registry.izelnakri.com
      secretName: docker-registry-cert
    
---
# Source: docker-registry/templates/pvc.yaml

