apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: docker-registry-cert-issuer
 namespace: default
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: contact@izelnakri.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: docker-registry-cert
   # Enable the HTTP-01 challenge provider
   http01: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-registry-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: docker-registry-cert-issuer
    certmanager.k8s.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/proxy-body-size: "900m" # allows limiting data sent per req
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: http-basic-auth
    # TODO: add http auth: nginx.ingress.kubernetes.io/auth-tls-secret: "<namespace>/<secretName>"
spec:
  tls:
  - hosts:
    - registry.izelnakri.com
    secretName: docker-registry-cert
  rules:
  - host: registry.izelnakri.com
    http:
      paths:
      - backend:
          serviceName: docker-registry
          servicePort: 5000
