kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
  - manifests.yaml
  - namespace.yaml
  - issuer.yaml
  - ingress.yaml
  - application.yaml
  # - role.yaml
  # - helm.yaml
