kind: pipeline
name: default
steps:
- name: test
  image: node
  commands:
  - cat .drone.yml
# NOTE: learn how to do branch filters: # you can write bash scripts with if checks to do certain things at certain times
