version: '3.2'

services:
  phoenix:
    build:
      context: ./backend
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
      MIX_ENV: test
    tty: true
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:10.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
networks:
  backend:
    driver: bridge
