FROM "node:14.2-slim"

ENV PORT=8080

WORKDIR /code/

ADD ["maps", "/code/maps"]
ADD ["package-lock.json", "package.json", "/code/"]

RUN npm install

ADD ["index.js", "paint.js", "painting.html", "/code/"]

CMD ["/bin/sh"]
