version: '3.2'
services:
  db:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: $PGUSER
      POSTGRES_USER: $PGPASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - backend_network
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    image: $BACKEND_IMAGE_NAME
    build:
      context: ./backend
      dockerfile: $BACKEND_DOCKERFILE
      cache_from:
        - $BASE_IMAGE
        - $BACKEND_IMAGE_CACHE
    environment:
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGPORT: 5432
      PGHOST: db
      MIX_ENV: $MIX_ENV
    tty: true
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - backend_network
    command: ["./scripts/setup-database.sh"]
  frontend:
    image: $FRONTEND_IMAGE_NAME
    tty: true
    build:
      context: ./frontend
      dockerfile: $FRONTEND_DOCKERFILE
      cache_from:
        - $BASE_IMAGE
        - $FRONTEND_IMAGE_CACHE
    ports:
      - "4200:4200"
    networks:
      - backend_network

volumes:
  pgdata:
networks:
  backend_network:
    driver: bridge
