apiVersion: v1
kind: Pod
metadata:
  name: drone
spec:
  containers:
    - name: drone
      image: "drone/drone:1.0.0"
      env:
      - name: DRONE_KUBERNETES_ENABLED
        value: "true"
      - name: DRONE_KUBERNETES_NAMESPACE
        value: default
      - name: DRONE_GITHUB_SERVER
        value: https://github.com
      - name: DRONE_GITHUB_CLIENT_ID
        value: 71011506da4614529cd2
      - name: DRONE_GITHUB_CLIENT_SECRET
        value: 77007f02a0c2398eeb78dde503feb28f10430f36
      - name: DRONE_RPC_SECRET
        value: bd737995b3866febbfa7dbd5fbce67cf
      - name: DRONE_SERVER_HOST
        value: localhost:8080
      - name: DRONE_SERVER_PROTO
        value: http
      ports:
      - containerPort: 80
      - containerPort: 443
# expose this as drone.izelnakri.com
