apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: application-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - drone.izelnakri.com
    - izelnakri.com
    secretName: letsencrypt-prod
  rules:
  - host: drone.izelnakri.com
    http:
      paths:
      - backend:
          serviceName: drone
          servicePort: 80
  - host: izelnakri.com
    http:
      paths:
      - backend:
          serviceName: izelnakri-com-service
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: izelnakri-com-deployment
  namespace: default
  labels:
    app: izelnakri-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izelnakri-com
  template:
    metadata:
      labels:
        app: izelnakri-com
    spec:
      containers:
        - name: izelnakri-com
          image: hashicorp/http-echo
          args:
            - "-text=setting up k8s"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: izelnakri-com-service
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: izelnakri-com
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: drone-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: contact@izelnakri.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: letsencrypt-prod
   # Enable the HTTP-01 challenge provider
   http01: {}
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: drone
#   namespace: default
# spec:
#  rules:
#  - host: drone.192.168.39.43.xip.io
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: drone
#          servicePort: http
# expose this as drone.izelnakri.com
