# remake values.yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: harbor

resources:
  - namespace.yaml
  - issuer.yaml
  - helm.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: izel-harbor-ingress-notary
  path: notary-ingress-patch.yaml

# # TODO: make secretNames only a single secret with hosts



# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: "izel-harbor-ingress"
