apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
data:
  digitalocean: |
    s3:
      endpoint: fra1.digitaloceanspaces.com
      bucket: izelnakri
      keyFormat: "my-artifacts\
        /{{workflow.creationTimestamp.Y}}\
        /{{workflow.creationTimestamp.m}}\
        /{{workflow.creationTimestamp.d}}\
        /{{workflow.name}}\
        /{{pod.name}}"
      accessKeySecret:
        name: do-spaces-keys
        key: access-key
      secretKeySecret:
        name: do-spaces-keys
        key: secret-key
