kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argo
resources:
  - manifests.yaml
  - namespace.yaml
  - issuer.yaml
  - ingress.yaml
  - role.yaml
  - artifact-repositories-configmap.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: do-spaces-keys
  files:
    - secrets/do-spaces/access-key
    - secrets/do-spaces/secret-key
