apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    template:                     # You should NEVER use "template" here. Use it under a "steps" or "dag" template (see above).
    templateRef:                  # You should NEVER use "templateRef" here. Use it under a "steps" or "dag" template (see above).
      name: workflow-template-1
      template: whalesay-template
    arguments:                    # Arguments here are ignored. Use them under a "steps" or "dag" template (see above).
      parameters:
      - name: message
        value: "hello world"


# apiVersion: argoproj.io/v1alpha1
# kind: Workflow
# metadata:
#   generateName: workflow-template-hello-world-
# spec:
#   entrypoint: whalesay
#   templates:
#   - name: whalesay
#     steps:                              # You should only reference external "templates" in a "steps" or "dag" "template".
#       - - name: call-whalesay-template
#           templateRef:                  # You can reference a "template" from another "WorkflowTemplate" using this field
#             name: workflow-template-1   # This is the name of the "WorkflowTemplate" CRD that contains the "template" you want
#             template: whalesay-template # This is the name of the "template" you want to reference
#           arguments:                    # You can pass in arguments as normal
#             parameters:
#             - name: message
#               value: "hello world"
