namespace: argo
releaseName: izel

imageNamespace: argoproj
ciImage: argoci
imageTag: v1.0.0-alpha2
imagePullPolicy: Always
workflowNamespace: argo

argo:
  imagesNamespace: argoproj
  installMinio: true
  minioBucketName: argo-artifacts
  useReleaseAsInstanceID: true
