apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    artifactRepository:
      s3:
        endpoint: fra1.digitaloceanspaces.com
        bucket: izelnakri
        keyFormat: "my-artifacts\
          /{{workflow.creationTimestamp.Y}}\
          /{{workflow.creationTimestamp.m}}\
          /{{workflow.creationTimestamp.d}}\
          /{{workflow.name}}\
          /{{pod.name}}"
        accessKeySecret:
          name: do-spaces-keys
          key: access-key
        secretKeySecret:
          name: do-spaces-keys
          key: secret-key
    executor:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 400m
          memory: 800Mi
