WARNING: This chart is deprecated
---
# Source: drone/templates/service-account-pipeline.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-drone-pipeline
  namespace: default
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
---
# Source: drone/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-drone
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
---
# Source: drone/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-drone
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
type: Opaque
data:
  
  secret: "WmhYc3ZlOXpzcjJONUpaU3FUUlJXYlZL"
---
# Source: drone/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-drone-source-control
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
type: Opaque
data:
---
# Source: drone/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: RELEASE-NAME-drone
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: drone/templates/role-pipeline.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: RELEASE-NAME-drone-pipeline
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
rules:
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
      - pods
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
# Source: drone/templates/role-binding-pipeline.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: RELEASE-NAME-drone-pipeline
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-drone-pipeline
    namespace: default
roleRef:
  kind: ClusterRole
  name: RELEASE-NAME-drone-pipeline
  apiGroup: rbac.authorization.k8s.io
---
# Source: drone/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: RELEASE-NAME-drone
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
      - update
---
# Source: drone/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RELEASE-NAME-drone
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: RELEASE-NAME-drone
subjects:
- kind: ServiceAccount
  name: RELEASE-NAME-drone
  namespace: default
---
# Source: drone/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-drone
  annotations:
  labels:
    app: drone
    chart: "drone-2.7.2"
    release: "RELEASE-NAME"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: drone
    release: "RELEASE-NAME"
    component: server
