apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: gitea-issuer
 namespace: harbor
spec:
 acme:
  # The ACME server URL
  # server: https://acme-staging-v02.api.letsencrypt.org/directory
  server: https://acme-v02.api.letsencrypt.org/directory
  # Email address used for ACME registration
  email: contact@izelnakri.com
  # Name of a secret used to store the ACME account private key
  privateKeySecretRef:
   name: gitea-tls
  http01: {}
  # solvers: # An empty 'selector' means that this solver matches all domains
  # - http01:
  #     ingress:
  #       class: nginx
