# apiVersion: certmanager.k8s.io/v1alpha1
# kind: ClusterIssuer
# metadata:
#  name: izelnakri-com-issuer
#  namespace: izelnakri-com
# spec:
#  acme:
#   # The ACME server URL
#   # server: https://acme-staging-v02.api.letsencrypt.org/directory
#   server: https://acme-v02.api.letsencrypt.org/directory
#   # Email address used for ACME registration
#   email: contact@izelnakri.com
#   # Name of a secret used to store the ACME account private key
#   privateKeySecretRef:
#    name: izelnakri-com-tls
#   http01: {}
#   # solvers: # An empty 'selector' means that this solver matches all domains
#   # - http01:
#   #     ingress:
#   #       class: nginx
# ---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: izelnakri-com-ingress
  namespace: izelnakri-com
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: izelnakri-com-issuer
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - izelnakri.com
    secretName: izelnakri-com-tls
  rules:
  - host: izelnakri.com
    http:
      paths:
      - backend:
          serviceName: izelnakri-com-service
          servicePort: 80
