kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - issuer.yaml
  - ingress.yaml
