apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stolon

resources:
  - namespace.yaml
  - helm.yaml

patchesJson6902:
# - target:
#     version: v1
#     kind: Service
#     name: izel-stolon-metrics
#   path: metrics-service-patch.yaml
- target:
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
    name: izel-stolon
  path: service-monitor-patch.yaml
