on: [push]

jobs:
  my_first_job:
    runs-on: ubuntu-18.04
    steps:
      - name: My first step
        uses: docker://alpine:3.8
      - name: Print uname
        run: uname -a
      - name: Print hello world
        run: echo "Hello world"

# name: CI
#
# on:
#   push:
#     branches:
#       - master
#       - 'v*' # older version branches
#     tags:
#       - '*'
#   pull_request: {}
#   schedule:
#   - cron:  '0 6 * * 0' # weekly, on sundays

# jobs:
#   test:
#     name: Tests
#     runs-on: ${{ matrix.os }}

#     strategy:
#       matrix:
#         node: ['10', '12']
#         os: [ubuntu-latest, macOS-latest, windows-latest]

#     steps:
#     - uses: actions/checkout@v1
#     - uses: volta-cli/action@v1
#       with:
#         node-version: ${{ matrix.node }}
#     - name: install dependencies
#       run: yarn
#     - name: test
#       run: yarn test
